apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tailwind-loadbalancer
spec:
  replicas: 2
  selector:
    matchLabels:
      name: tailwind-loadbalancer
  template:
    metadata:
      name: tailwind-loadbalancer
      labels:
        name: tailwind-loadbalancer
    spec:
      containers:
        - name : tailwind-loadbalancer
          image: dickyfahlevi21/microservices1:v1
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: tailwind-service-loadbalancer
spec:
  type: LoadBalancer
  selector: 
    name: tailwind-loadbalancer
  ports:
    - port: 80
      targetPort: 80
