apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tailwind-nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      name: tailwind-nodeport
  template:
    metadata:
      name: tailwind-nodeport
      labels:
        name: tailwind-nodeport
    spec:
      containers:
        - name : tailwind-nodeport
          image: dickyfahlevi21/microservices1:v1
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: tailwind-service-nodeport
spec:
  type: NodePort
  selector: 
    name: tailwind-nodeport
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
